/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import DB.EmpleadoVA;
import Datos.Empleado;
import javax.swing.JOptionPane;

/**
 *
 * @author josti
 */
public class Jframe extends javax.swing.JFrame {
    private Empleado emp =  new Empleado();
    private EmpleadoVA empva = new EmpleadoVA();
    private int cd = 0;
    private String bx = "N";
    private String mj = "";
    
    
    
    /**
     * Creates new form Jframe
     */
    public Jframe() {
     
        initComponents();
        listarEmpleado();  
        btneliminar.setVisible(false);
        btneditar.setVisible(false);
        
    }
    
    public void listarEmpleado(){
        empva.listarEmpleado(jTable1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtrut = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtapellidop = new javax.swing.JTextField();
        txtapellidom = new javax.swing.JTextField();
        cmbtipoem = new javax.swing.JComboBox<>();
        txtnumero = new javax.swing.JTextField();
        lblrut = new javax.swing.JLabel();
        lblnombre = new javax.swing.JLabel();
        lblapellidop = new javax.swing.JLabel();
        lblapellidom = new javax.swing.JLabel();
        lblcmb = new javax.swing.JLabel();
        lbltelefono = new javax.swing.JLabel();
        box = new javax.swing.JCheckBox();
        btnguardar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btneditar = new javax.swing.JButton();
        btnlistar = new javax.swing.JButton();
        txttipo = new javax.swing.JTextField();
        txtcontrato = new javax.swing.JTextField();
        jbox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtrut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrutActionPerformed(evt);
            }
        });

        cmbtipoem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jefe TI", "Programador", "Cajera", "Supervisor" }));
        cmbtipoem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbtipoemActionPerformed(evt);
            }
        });

        lblrut.setText("Rut");

        lblnombre.setText("Nombre");

        lblapellidop.setText("Apelllido P");

        lblapellidom.setText("Apellido M");

        lblcmb.setText("Tipo Empleado");

        lbltelefono.setText("Telefono");

        box.setText("Contrato Indefinido");
        box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxActionPerformed(evt);
            }
        });

        btnguardar.setText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btneditar.setText("Modificar");
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });

        btnlistar.setText("Actualizar");
        btnlistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlistarActionPerformed(evt);
            }
        });

        jbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Guardar", "Modificar", "Eliminar" }));
        jbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbltelefono)
                                .addGap(20, 20, 20))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblapellidom)
                                    .addComponent(lblcmb)
                                    .addComponent(lblapellidop)
                                    .addComponent(lblnombre)
                                    .addComponent(lblrut))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtapellidop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtapellidom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtnumero, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cmbtipoem, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txttipo))
                                .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtrut, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(box)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtcontrato, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(btnguardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btneliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btneditar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(btnlistar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblrut)
                    .addComponent(txtrut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblnombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtapellidop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblapellidop))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtapellidom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblapellidom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbtipoem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblcmb)
                    .addComponent(txttipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbltelefono))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(box, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcontrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnguardar)
                    .addComponent(btneliminar)
                    .addComponent(btneditar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnlistar)
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        // TODO add your handling code here:
         emp.setRut(txtrut.getText());
         emp.setNombre(txtnombre.getText());
         emp.setApellidom(txtapellidom.getText());
         emp.setApellidop(txtapellidop.getText());
         emp.setTipoem(cd);
          int a = Integer.parseInt(txtnumero.getText());
         emp.setTelefono(a);
         emp.setContrato(bx);
         mj = empva.agregarEmpleado(emp);
         JOptionPane.showMessageDialog(rootPane, mj);
        limpiar();
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        // TODO add your handling code here:
            String a = txtrut.getText();
            mj = empva.eliminarEmpleado(a);
            JOptionPane.showMessageDialog(rootPane, mj);
            limpiar();
    }//GEN-LAST:event_btneliminarActionPerformed

    private void txtrutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrutActionPerformed

    private void btnlistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlistarActionPerformed
        // TODO add your handling code here:
        listarEmpleado();
    }//GEN-LAST:event_btnlistarActionPerformed

    private void cmbtipoemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbtipoemActionPerformed
        // TODO add your handling code here:
        if ("Jefe TI".equals(cmbtipoem.getSelectedItem())) {
                cd = 1;
        }
        if ("Programador".equals(cmbtipoem.getSelectedItem())) {
                cd = 2;
        } 
        if ("Cajera".equals(cmbtipoem.getSelectedItem())) {
                cd = 3;
        } 
         if ("Supervisor".equals(cmbtipoem.getSelectedItem())) {
                cd = 4;
        } 
    }//GEN-LAST:event_cmbtipoemActionPerformed

    private void boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxActionPerformed
        // TODO add your handling code here:
       
       if(box.isSelected()) {
           System.out.println("ddd");
           bx = "S";
       }if(!box.isSelected()){
           bx = "N";
       }
    }//GEN-LAST:event_boxActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int seleccion = jTable1.rowAtPoint(evt.getPoint()); 
        txtrut.setText(jTable1.getValueAt(seleccion, 0)+"");
        txtnombre.setText(jTable1.getValueAt(seleccion, 1)+"");
        txtapellidop.setText(jTable1.getValueAt(seleccion, 2)+"");
        txtapellidom.setText(jTable1.getValueAt(seleccion, 3)+"");
        txttipo.setText(jTable1.getValueAt(seleccion, 4)+"");
        txtnumero.setText(jTable1.getValueAt(seleccion, 5)+"");
        txtcontrato.setText(jTable1.getValueAt(seleccion, 6)+"");
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
        // TODO add your handling code here:
         emp.setRut(txtrut.getText());
         emp.setNombre(txtnombre.getText());
         emp.setApellidom(txtapellidom.getText());
         emp.setApellidop(txtapellidop.getText());
         emp.setTipoem(cd);
          int a = Integer.parseInt(txtnumero.getText());
         emp.setTelefono(a);
         emp.setContrato(bx);
         mj = empva.modificarEmpleado(emp);
         JOptionPane.showMessageDialog(rootPane, mj);
        
    }//GEN-LAST:event_btneditarActionPerformed

    private void jboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jboxActionPerformed
        // TODO add your handling code here:
        if ("Guardar".equals(jbox.getSelectedItem())) {
            Inicio();
        }
        if ("Modificar".equals(jbox.getSelectedItem())) {
            Modificar();
        } 
        if("Eliminar".equals(jbox.getSelectedItem())) {
            Eliminar();
            
        }
    }//GEN-LAST:event_jboxActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
         
        java.awt.EventQueue.invokeLater(new Runnable() {
         
            
            
            public void run() {
                new Jframe().setVisible(true);
            }
       
        
   
        });
            
        
    }

    
    
    
    
    
    
    

    
    public void limpiar(){
         txtrut.setText("");
         txtnombre.setText("");
         txtapellidom.setText("");
         txtapellidop.setText("");
         txtnumero.setText("");


        }
    
    
   public void   Inicio(){
box.setVisible(true);
 btneditar.setVisible(false);
 btneliminar.setVisible(false);
btnguardar.setVisible(true);
  btnlistar.setVisible(true);
  cmbtipoem.setVisible(true);
    jbox.setVisible(true);
     lblapellidom.setVisible(true);
     lblapellidop.setVisible(true);
     lblcmb.setVisible(true);
    lblnombre.setVisible(true);
     lblrut.setVisible(true);
     lbltelefono.setVisible(true);
     txtapellidom.setVisible(true);
     txtapellidop.setVisible(true);
    txtcontrato.setVisible(false);
     txtnombre.setVisible(true);
    txtnumero.setVisible(true);
     txtrut.setVisible(true);
     txttipo.setVisible(false);
       
       
   }
    public void Modificar(){
        box.setVisible(false);
 btneditar.setVisible(true);
 btneliminar.setVisible(false);
btnguardar.setVisible(false);
  btnlistar.setVisible(true);
  cmbtipoem.setVisible(false);
    jbox.setVisible(true);
     lblapellidom.setVisible(true);
     lblapellidop.setVisible(true);
     lblcmb.setVisible(true);
    lblnombre.setVisible(true);
     lblrut.setVisible(true);
     lbltelefono.setVisible(true);
     txtapellidom.setVisible(true);
     txtapellidop.setVisible(true);
    txtcontrato.setVisible(true);
     txtnombre.setVisible(true);
    txtnumero.setVisible(true);
     txtrut.setVisible(true);
     txttipo.setVisible(true);
    }
    
    
        public void Eliminar(){
        box.setVisible(false);
       btneditar.setVisible(false);
        btneliminar.setVisible(true);
      btnguardar.setVisible(false);
    btnlistar.setVisible(true);
     cmbtipoem.setVisible(false);
    jbox.setVisible(true);
     lblapellidom.setVisible(false);
     lblapellidop.setVisible(false);
     lblcmb.setVisible(false);
    lblnombre.setVisible(false);
     lblrut.setVisible(true);
     lbltelefono.setVisible(false);
     txtapellidom.setVisible(false);
     txtapellidop.setVisible(false);
    txtcontrato.setVisible(false);
     txtnombre.setVisible(false);
    txtnumero.setVisible(false);
     txtrut.setVisible(true);
     txttipo.setVisible(false);
    }
    
    
    
    
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox box;
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnlistar;
    private javax.swing.JComboBox<String> cmbtipoem;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> jbox;
    private javax.swing.JLabel lblapellidom;
    private javax.swing.JLabel lblapellidop;
    private javax.swing.JLabel lblcmb;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JLabel lblrut;
    private javax.swing.JLabel lbltelefono;
    private javax.swing.JTextField txtapellidom;
    private javax.swing.JTextField txtapellidop;
    private javax.swing.JTextField txtcontrato;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtnumero;
    private javax.swing.JTextField txtrut;
    private javax.swing.JTextField txttipo;
    // End of variables declaration//GEN-END:variables
}
